services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_EXPRESS_MIDDLEWARE: "http://express:5000"
    depends_on:
      - express
      - flask

  express:
    build:
      context: ./server/express
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/express/.env
    volumes:
      - ./server/express:/server/express
      - /server/express/node_modules
    depends_on:
      - flask

  flask:
    build:
      context: ./server/flask
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server/flask:/server/flask
